# Generated by Django 5.2.14 on 2026-05-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPricing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('model_keyword', models.CharField(db_index=True, help_text='模型名关键词', max_length=100)),
                ('provider_name', models.CharField(blank=True, help_text='供应商名，NULL 表示通用', max_length=100, null=True)),
                ('input_price', models.DecimalField(decimal_places=6, help_text='输入价格（元/千token）', max_digits=10)),
                ('output_price', models.DecimalField(decimal_places=6, help_text='输出价格（元/千token）', max_digits=10)),
                ('currency', models.CharField(default='CNY', max_length=3)),
                ('is_builtin', models.BooleanField(default=False, help_text='是否内置价格')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'model_pricing',
                'ordering': ['model_keyword'],
            },
        ),
    ]
