# Generated by Django 5.2.14 on 2026-05-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpricing',
            name='input_price_cached',
            field=models.DecimalField(decimal_places=6, default=0, help_text='输入价格-命中缓存（元/千token）', max_digits=10),
        ),
        migrations.AlterField(
            model_name='modelpricing',
            name='input_price',
            field=models.DecimalField(decimal_places=6, help_text='输入价格-未命中缓存（元/千token）', max_digits=10),
        ),
    ]
