# Generated by Django 5.2.14 on 2026-05-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trigger_cost', models.DecimalField(decimal_places=2, help_text='触发时的费用', max_digits=10)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('channel', models.CharField(max_length=20)),
                ('send_status', models.CharField(choices=[('sent', '已发送'), ('failed', '发送失败')], default='sent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'alert_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='规则名称', max_length=100)),
                ('rule_type', models.CharField(choices=[('daily', '每日'), ('monthly', '每月'), ('total', '累计')], help_text='规则类型', max_length=20)),
                ('threshold_yuan', models.DecimalField(decimal_places=2, help_text='告警阈值（元）', max_digits=10)),
                ('alert_channel', models.CharField(choices=[('webhook', 'Webhook'), ('email', 'Email')], help_text='告警渠道', max_length=20)),
                ('webhook_url', models.CharField(blank=True, help_text='Webhook URL', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'budget_rules',
                'ordering': ['-created_at'],
            },
        ),
    ]
