# Generated by Django 5.2.14 on 2026-05-31 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alertlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetrule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertlog',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_logs', to='alerts.budgetrule'),
        ),
    ]
