# Generated by Django 5.2.14 on 2026-06-03 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_initial'),
        ('gateway', '0010_modelrouting_max_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetrule',
            name='api_key',
            field=models.ForeignKey(blank=True, help_text='关联的 API Key，为空表示用户级规则', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_rules', to='gateway.apikey'),
        ),
        migrations.AddField(
            model_name='budgetrule',
            name='auto_disable',
            field=models.BooleanField(default=False, help_text='超预算后自动禁用 Key'),
        ),
    ]
