# Generated by Django 5.2.14 on 2026-06-04 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alertnotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='策略名称', max_length=100)),
                ('retention_days', models.IntegerField(default=30, help_text='保留天数（超过此天数的日志将被自动删除）')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_retention_policy',
                'ordering': ['-created_at'],
            },
        ),
    ]
