# Generated by Django 5.2.14 on 2026-05-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Key 名称，如'生产环境'", max_length=100)),
                ('key_prefix', models.CharField(help_text='前缀，用于快速查找', max_length=16)),
                ('key_hash', models.CharField(help_text='SHA256 hash，不存明文', max_length=128)),
                ('permissions', models.JSONField(default=dict, help_text='{"read": true, "write": true}')),
                ('rate_limit_rpm', models.IntegerField(default=60, help_text='每分钟请求数限制')),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMCallLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('agent_id', models.CharField(blank=True, help_text='来自请求头 X-Agent-Id', max_length=100, null=True)),
                ('model', models.CharField(max_length=100)),
                ('input_tokens_reported', models.IntegerField(blank=True, help_text='上游返回的 input tokens', null=True)),
                ('output_tokens_reported', models.IntegerField(blank=True, help_text='上游返回的 output tokens', null=True)),
                ('input_tokens_estimated', models.IntegerField(blank=True, help_text='本地估算的 input tokens', null=True)),
                ('output_tokens_estimated', models.IntegerField(blank=True, help_text='本地估算的 output tokens', null=True)),
                ('data_source', models.CharField(help_text='provider / estimated / mixed', max_length=20)),
                ('cost_yuan', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('is_error', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'llm_call_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='供应商名称', max_length=100)),
                ('base_url', models.CharField(help_text='API 基础地址', max_length=500)),
                ('api_key_enc', models.TextField(help_text='加密存储的 API Key')),
                ('status', models.CharField(choices=[('active', 'active'), ('disabled', 'disabled'), ('error', 'error')], default='active', max_length=20)),
                ('detect_result', models.JSONField(blank=True, help_text='自动检测结果', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'providers',
                'ordering': ['-created_at'],
            },
        ),
    ]
