# Generated by Django 5.2.14 on 2026-05-31 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gateway', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='llmcalllog',
            name='api_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='gateway.apikey'),
        ),
        migrations.AddField(
            model_name='llmcalllog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='provider',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='llmcalllog',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='gateway.provider'),
        ),
        migrations.AddIndex(
            model_name='llmcalllog',
            index=models.Index(fields=['user', 'created_at'], name='idx_user_time'),
        ),
        migrations.AddIndex(
            model_name='llmcalllog',
            index=models.Index(fields=['agent_id', 'created_at'], name='idx_agent_time'),
        ),
        migrations.AddIndex(
            model_name='llmcalllog',
            index=models.Index(fields=['model'], name='idx_model'),
        ),
        migrations.AddIndex(
            model_name='llmcalllog',
            index=models.Index(fields=['created_at'], name='idx_created_at'),
        ),
    ]
