# Generated by Django 5.2.14 on 2026-05-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='key_plain',
            field=models.CharField(default='', help_text='完整 Key（内部平台用）', max_length=128),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key_hash',
            field=models.CharField(help_text='SHA256 hash', max_length=128),
        ),
    ]
