# Generated by Django 5.2.14 on 2026-06-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0003_apikey_key_plain_alter_apikey_key_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='model_prefix',
            field=models.CharField(blank=True, default='', help_text='模型前缀，逗号分隔。如 mimo-,deepseek-。用于自动路由', max_length=200),
        ),
    ]
