# Generated by Django 5.2.14 on 2026-06-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0004_provider_model_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='health_status',
            field=models.CharField(default='unknown', help_text='健康状态: healthy/unhealthy/unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='provider',
            name='last_health_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
