# Generated by Django 5.2.14 on 2026-06-01 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0005_provider_health_status_provider_last_health_check'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRouting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(db_index=True, help_text='完整模型名，如 mimo-v2.5-pro', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_routings', to='gateway.provider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_routings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'model_routing',
                'ordering': ['model_name'],
                'unique_together': {('user', 'model_name')},
            },
        ),
    ]
