# Generated by Django 5.2.14 on 2026-06-01 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0006_modelrouting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmcalllog',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='gateway.apikey'),
        ),
    ]
