# Generated by Django 5.2.14 on 2026-06-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0007_alter_llmcalllog_api_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelrouting',
            options={'ordering': ['model_name', 'priority']},
        ),
        migrations.AlterUniqueTogether(
            name='modelrouting',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='modelrouting',
            name='priority',
            field=models.IntegerField(default=1, help_text='优先级，1=最高。同名模型按优先级排序'),
        ),
    ]
