# Generated by Django 5.2.14 on 2026-06-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0008_alter_modelrouting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='agent_id',
            field=models.CharField(blank=True, default='', help_text='Agent 标识，如 customer-service', max_length=100),
        ),
        migrations.AddField(
            model_name='apikey',
            name='agent_name',
            field=models.CharField(blank=True, default='', help_text='Agent 显示名，如 客服 Bot', max_length=100),
        ),
        migrations.AddField(
            model_name='apikey',
            name='allowed_models',
            field=models.JSONField(blank=True, default=list, help_text='可用模型列表，空=不限制'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='月度预算（元），0=不限制', max_digits=10),
        ),
    ]
