# Generated by Django 5.2.14 on 2026-06-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0009_apikey_agent_id_apikey_agent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrouting',
            name='max_tokens',
            field=models.IntegerField(default=0, help_text='模型最大 token 数，0=不限制'),
        ),
    ]
